### PR TITLE
Allow circle border color to be configurable through the 'circleBorde…

### PR DESCRIPTION
**Pull request by darkrift**
…rColor' props

### CODE REVIEW

**Comment by darkrift** [comment]
@shahen94 What is the frequency of your release or what are the gates that determines if you make a new release ?

Are you are waiting for the other issue about text color ?

**Comment by mrkirchner** [comment]
@shahen94 I just yarn installed this switch and i am not seeing the circle border color changes in the version pulled from NPM.

**Comment by darkrift** [comment]
You can yarn install the git repo in the mean time, I yarn installed my fork for my project untill this get published.

**Comment by surfercoder** [comment]
Hello guys,

I know you have closed a previous issue related to it, but checking the code it seems to be that even when you set the circleBorderColor property, it always has the same color, a black one.

In the example, you will see that I set a border with with 5 just to make it quite clear and visible:

This is the code I have:

<Switch
  backgroundActive="rgb(210, 210, 210)"
  backgroundInactive="rgb(210, 210, 210)"
  circleActiveColor="rgb(255, 85, 72)"
  circleBorderColor="rgb(210, 210, 210)"
  circleBorderWidth={5}
  circleInActiveColor="rgb(230, 230, 230)"
  onValueChange={onValueChange}
  value={value}
/>

And this is what I am getting:

[https://www.dropbox.com/s/pl03ni6alohx1fs/Screen%20Shot%202018-08-21%20at%2012.33.12.png?dl=0](url)

Have you added this improvement in any version? I have added the latest one but no luck so far, and since I saw you closed the issue I want to double check this.

Thanks for your help in advance.

Best regards.

**Comment by duytq94** [comment]
I have the same too, not change at all. But I see `circleBorderActiveColor` and `circleBorderInactiveColor`. Not `circleBorderColor` like you said @surfercoder 
image.
Btw, two of them don't work.

**Pull request merged**
